### ISSUE TITLE
这是什么版本cocos2d写的

### ISSUE THREAD

**Issue by wengxianxun** [lfeng1420/BrickGame#4]
这是什么版本cocos2d写的

**Comment by lfeng1420** [comment]
Cocos2dx 3.2

**Comment by wengxianxun** [comment]
![249709dc-f16a-4d0a-a399-023340489416](https://cloud.githubusercontent.com/assets/831898/22233385/02520326-e22b-11e6-86c4-cc4fd24f0c7d.png)
我用3.2aplha版，出现这个问题。

**Comment by lfeng1420** [comment]
@wengxianxun 我之前改了底层的代码，稍等我上传下

**Comment by lfeng1420** [comment]
已经上传了，覆盖下cocos2d那个目录，还有编译报错的话再截图发下

**Comment by wengxianxun** [comment]
![44318c14-d961-4df3-9bdc-751cf0074c09](https://cloud.githubusercontent.com/assets/831898/22236822/1d6229da-e243-11e6-83b1-72d5d6615207.png)

**Comment by wengxianxun** [comment]
我是3.2alpha版本，在xcode中建的项目，会不会很多东西不一样

**Comment by wengxianxun** [comment]
实际上我的第一个截图那个是Button类并没有那几个方法，那几个方法应该是你添加上去的吧

**Comment by lfeng1420** [comment]
那几个方法是我加上去的

**Comment by lfeng1420** [comment]
3.2alpha版我没用过，我这边也没有苹果系统，so...我也不知道有什么不一样

**Comment by wengxianxun** [comment]
能不能把你的cocos2d发一份给我

**Comment by lfeng1420** [comment]
是还有编译问题么？cocos2d这个文件夹有点大，不太好发送

**Comment by lfeng1420** [comment]
给我个邮箱地址吧，我发给你

**Comment by wengxianxun** [comment]
wengxianxun@Hotmail.com

**Comment by lfeng1420** [comment]
晚上回去我发给你吧
