### ISSUE TITLE
怎么运行项目

### ISSUE THREAD

**Issue by wengxianxun** [lfeng1420/BrickGame#6]
怎么运行项目

**Comment by lfeng1420** [comment]
1、新建一个cocos2dx 3.2项目；
2、拷贝替换 Classes / Resources / cocos2d / proj.win32 / proj.android / proj.wp8-xaml 这几个文件夹；
3、win32：VS打开proj.win32下的BrickGame.sln，编译之后运行；
     wp：VS打开proj.wp8-xaml下的BrickGame.sln，编译之后运行；
     android：eclipse导入android项目（proj.android），编译之后导出apk。

**Comment by wengxianxun** [comment]
怎么用android studio打开项目

**Comment by lfeng1420** [comment]
android studio我没怎么用过，所以不太清楚，抱歉
